language: 
  - java
jdk: 
  - oraclejdk8
before_install: 
  - sudo apt-get update
  - sudo apt-get install libaudit-dev auditd libfuse-dev fuse pkg-config uthash-dev tcsh
script: 
  - ./configure;
  - make
  - sudo make install
notifications:
  email:
    - raza.ahmad@sri.com
    - hassaan.irshad@sri.com
